/// <reference types="vite/client" />
/**
 * Auto-generated by nextjs-to-tanstack: bootstraps i18next for react-i18next.
 * Sync locale with your \`/{-$locale}/…\` routes (e.g. i18n.changeLanguage) as needed.
 */
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const DEFAULT_LNG = "en";
const LOCALES = ["en", "de"] as const;

async function loadAllResources(): Promise<
  Record<string, { common: Record<string, unknown> }>
> {
  if (import.meta.env.SSR) {
    const { readFileSync, existsSync } = await import("node:fs");
    const { join } = await import("node:path");
    const out: Record<string, { common: Record<string, unknown> }> = {};
    for (const lng of LOCALES) {
      const p = join(process.cwd(), "public", "locales", lng, "common.json");
      if (existsSync(p)) {
        out[lng] = {
          common: JSON.parse(readFileSync(p, "utf8")) as Record<string, unknown>,
        };
      }
    }
    return out;
  }
  const out: Record<string, { common: Record<string, unknown> }> = {};
  await Promise.all(
    LOCALES.map(async (lng) => {
      const res = await fetch(`/locales/${lng}/common.json`);
      if (res.ok) {
        out[lng] = { common: (await res.json()) as Record<string, unknown> };
      }
    }),
  );
  return out;
}

const resources = await loadAllResources();

await i18n.use(initReactI18next).init({
  resources,
  lng: DEFAULT_LNG,
  fallbackLng: DEFAULT_LNG,
  supportedLngs: [...LOCALES],
  ns: ["common"],
  defaultNS: "common",
  interpolation: { escapeValue: false },
  react: { useSuspense: false },
});

export default i18n;
