import type { Metadata } from "next";
import { Outlet, createRootRoute, HeadContent, Scripts } from '@tanstack/react-router';
import appCss from './globals.css?url';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const Route = createRootRoute({
  component: RootLayout,
});

function RootLayout() {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        <Outlet />
        <Scripts />
      </body>
    </html>
  );
}
