/**
 * Final workflow step: write a short manual checklist beside `package.json`.
 * Most actionable follow-ups are also emitted in source as `// TODO:` comments
 * (R10 / R10b); this file points to that search and keeps install / monorepo /
 * tooling reminders.
 *
 * Triggers off `package.json`; only writes when this package was touched by the
 * codemod (`@tanstack/react-start` added in R11).
 *
 * Does not edit `package.json`; writes `TANSTACK_MIGRATION_NEXT_STEPS.md` next
 * to it (e.g. `apps/web/TANSTACK_MIGRATION_NEXT_STEPS.md` in a monorepo).
 */

import type { Codemod } from "codemod:ast-grep";
import type JSON_TYPES from "codemod:ast-grep/langs/json";
import { getState } from "codemod:workflow";
import { useMetricAtom } from "codemod:metrics";
import { writeFileSync } from "fs";
import { join } from "path";
import {
  buildMigrationRunSummarySection,
  type R10Accum,
  type R10bAccum,
} from "../utils/migration-run-report.ts";
import { getFilename, normalizePath, relativeToTargetDir } from "../utils/paths.ts";

const OUTFILE = "TANSTACK_MIGRATION_NEXT_STEPS.md";

const r10Metric = useMetricAtom("nextjs-to-tanstack-r10-async-await");
const r10bMetric = useMetricAtom("nextjs-to-tanstack-r10b-next-import");

function inferPackageRoot(packageJsonPath: string): string {
  const idx = packageJsonPath.lastIndexOf("/");
  if (idx === -1) return ".";
  return packageJsonPath.slice(0, idx);
}

function mergedDeps(pkg: Record<string, unknown>): Record<string, string> {
  const d = pkg.dependencies as Record<string, string> | undefined;
  const dev = pkg.devDependencies as Record<string, string> | undefined;
  return { ...(d ?? {}), ...(dev ?? {}) };
}

const GUIDE = `# TanStack Start — manual follow-up after the codemod

This file was generated by the **nextjs-to-tanstack** codemod. Keep using the official guide: [Migrate from Next.js](https://tanstack.com/start/latest/docs/framework/react/migrate-from-next-js).

## Optional: i18n (TanStack Router \`/{-$locale}/…\`)

When this package had Next.js \`i18n\` (often via \`next-i18next.config.*\`), routes were moved under **\`src/app/{-$locale}/**\` and \`createFileRoute\` IDs use the optional segment **\`/{-$locale}\`** so the same route matches both the default locale (no prefix) and prefixed locales — see [Internationalization (i18n)](https://tanstack.com/router/latest/docs/guide/internationalization-i18n).

- If **\`.codemod/i18n.json\`** exists, it lists the locales the codemod detected. The workflow also emits **\`src/i18n.ts\`** (when absent) and wraps **\`__root.tsx\`** with **\`I18nextProvider\`**, and preloads **\`import \"./i18n\"\`** from **\`router.tsx\`** so **\`react-i18next\`** receives a real **\`i18next\`** instance (replacing **\`next-i18next\`** / \`serverSideTranslations\`).
- Wire **\`react-i18next\`** / **Paraglide** to the active locale (often \`Route.useParams().locale\` or router \`rewrite\` for URL localization — see the same doc and the [Paraglide + TanStack](https://github.com/TanStack/router/tree/main/examples/react/i18n-paraglide) example).
- Internal **\`Link to="…"\`** paths may need \`params\` updates so the optional \`locale\` is preserved when switching languages.

## 1. In-repo TODO markers (start here)

The workflow inserts single-line source comments you can search for:

\`\`\`bash
rg '// TODO:'
\`\`\`

- **R10** — \`// TODO: … Route.loader …\` before \`createFileRoute\` components that still use **top-level \`await\`** (move data into \`Route.loader\` or server functions).
- **R10b** — the same \`// TODO:\` prefix **immediately before each surviving \`from "next/…"\` import**, plus one file-level note for **\`middleware.ts\` / \`middleware.tsx\`** when it still imports from Next.

Resolve or delete each marker as you port the code. Safe \`next/dynamic\` / external \`next/script\` patterns are already rewritten earlier in the workflow; anything left usually needs a manual decision.

## 2. Install and run

- Install dependencies (\`pnpm install\`, \`yarn\`, or \`npm install\`).
- If **\`next-auth\`**, **\`next-i18next\`**, or **\`@sentry/nextjs\`** (etc.) remain, replace or reconfigure them — **\`next\`** is removed from \`package.json\` and those packages often expect it as a peer.
- Run **\`pnpm dev\` / \`npm run dev\` / \`vite dev\`** and fix compile errors.

## 3. Review (not fully automatable)

- **Metadata / SEO** — compare \`head()\` with what you had under \`export const metadata\`.
- **Monorepos** — other packages may still target Next; use **\`-t\`** on one app when you want a narrow run. Shared code that imports **\`next/navigation\`** still needs **\`@tanstack/react-router\`** at call sites.
- **Tooling** — when there are no Next-adjacent peers, the codemod adjusts **\`tsconfig\`**, **\`.eslintrc.json\`**, **\`README.md\`**, and **\`.github/workflows/\`**. Double-check **flat ESLint** (\`eslint.config.*\`), root CI, and **JSONC** by hand.
- **Pages Router leftovers** — if the project used \`pages/\`, any files that were not merged into routes (e.g. \`_document.tsx\`) were moved to **\`migrated-from-pages/\`** at the package root. Port or delete them, then remove that folder.
`;

const REFERENCE_LINKS = `## Reference links

- [TanStack Router — routing](https://tanstack.com/router/latest/docs/framework/react/routing/routing-concepts)
- [Server routes](https://tanstack.com/start/latest/docs/framework/react/guide/server-routes)
- [Server functions](https://tanstack.com/start/latest/docs/framework/react/guide/server-functions)
`;

const codemod: Codemod<JSON_TYPES> = async (root, options) => {
  const file = getFilename(root);
  if (!file.endsWith("/package.json") && !file.endsWith("package.json")) {
    return null;
  }

  const rootNode = root.root();
  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(rootNode.text()) as Record<string, unknown>;
  } catch {
    return null;
  }

  const deps = mergedDeps(pkg);
  if (!deps["@tanstack/react-start"]) {
    return null;
  }

  const dir = inferPackageRoot(file);
  const pkgRoot = normalizePath(dir);
  const r10 = getState<R10Accum>(`mtg:r10:${pkgRoot}`);
  const r10b = getState<R10bAccum>(`mtg:r10b:${pkgRoot}`);
  const summary = buildMigrationRunSummarySection({
    packageRoot: relativeToTargetDir(dir, options.targetDir ?? dir),
    r10,
    r10b,
    r10Metric,
    r10bMetric,
  });
  const body = `${GUIDE.trimEnd()}\n\n${summary.trimEnd()}\n\n${REFERENCE_LINKS.trimEnd()}\n`;
  writeFileSync(join(dir, OUTFILE), body);
  return null;
};

export default codemod;
