/**
 * Final workflow step: write a short manual checklist beside `package.json`.
 * Most actionable follow-ups are also emitted in source as `// TODO:` comments
 * (R10 / R10b / R4e–R4i); this file points to that search and keeps install / monorepo /
 * tooling reminders.
 *
 * Triggers off `package.json`; only writes when this package was touched by the
 * codemod (`@tanstack/react-start` added in R11).
 *
 * Does not edit `package.json`; writes `TANSTACK_MIGRATION_NEXT_STEPS.md` next
 * to it (e.g. `apps/web/TANSTACK_MIGRATION_NEXT_STEPS.md` in a monorepo), and
 * appends `TANSTACK_MIGRATION_NEXT_STEPS.md` + `migrated-from-pages/` to
 * `.gitignore` beside that manifest (creates `.gitignore` if missing).
 */

import type { Codemod } from "codemod:ast-grep";
import type JSON_TYPES from "codemod:ast-grep/langs/json";
import { getState } from "codemod:workflow";
import { useMetricAtom } from "codemod:metrics";
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import {
  buildMigrationRunSummarySection,
  type R10Accum,
  type R10bAccum,
} from "../utils/migration-run-report.ts";
import { getFilename, normalizePath, relativeToTargetDir } from "../utils/paths.ts";

const OUTFILE = "TANSTACK_MIGRATION_NEXT_STEPS.md";

const r10Metric = useMetricAtom("nextjs-to-tanstack-r10-async-await");
const r10bMetric = useMetricAtom("nextjs-to-tanstack-r10b-next-import");

function inferPackageRoot(packageJsonPath: string): string {
  const idx = packageJsonPath.lastIndexOf("/");
  if (idx === -1) return ".";
  return packageJsonPath.slice(0, idx);
}

function mergedDeps(pkg: Record<string, unknown>): Record<string, string> {
  const d = pkg.dependencies as Record<string, string> | undefined;
  const dev = pkg.devDependencies as Record<string, string> | undefined;
  return { ...(d ?? {}), ...(dev ?? {}) };
}

const GITIGNORE_BLOCK_HEADER = "# nextjs-to-tanstack codemod";

/** Same dir as OUTFILE — keep checklist + Pages backup trees out of version control unless opted in. */
function mergeMigrationGitignore(packageRoot: string): void {
  const gitignorePath = join(packageRoot, ".gitignore");
  let raw = "";
  try {
    raw = readFileSync(gitignorePath, "utf8");
  } catch {
    /* create new */
  }
  const nonemptyLines = raw
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);
  const guideOk = nonemptyLines.some((l) => l === "TANSTACK_MIGRATION_NEXT_STEPS.md");
  const migratedOk = nonemptyLines.some(
    (l) => l === "migrated-from-pages" || l === "migrated-from-pages/",
  );
  if (guideOk && migratedOk) {
    return;
  }
  const linesAppend: string[] = [];
  if (!guideOk) {
    linesAppend.push("TANSTACK_MIGRATION_NEXT_STEPS.md");
  }
  if (!migratedOk) {
    linesAppend.push("migrated-from-pages/");
  }
  const sep =
    raw.length === 0 ? "" : raw.endsWith("\n") ? "\n" : "\n\n";
  const block = `${GITIGNORE_BLOCK_HEADER}\n${linesAppend.join("\n")}\n`;
  writeFileSync(gitignorePath, `${raw}${sep}${block}`);
}

const GUIDE = `# TanStack Start — manual follow-up after the codemod

This file was generated by the **nextjs-to-tanstack** codemod. Keep using the official guide: [Migrate from Next.js](https://tanstack.com/start/latest/docs/framework/react/migrate-from-next-js).

## Optional: i18n (TanStack Router \`/{-$locale}/…\`)

When this package had Next.js \`i18n\` (often via \`next-i18next.config.*\`), routes were moved under **\`src/app/{-$locale}/**\` and \`createFileRoute\` IDs use the optional segment **\`/{-$locale}\`** so the same route matches both the default locale (no prefix) and prefixed locales — see [Internationalization (i18n)](https://tanstack.com/router/latest/docs/guide/internationalization-i18n).

- If **\`.codemod/i18n.json\`** exists, it lists the locales the codemod detected. The workflow also emits **\`src/i18n.ts\`** (when absent) and wraps **\`__root.tsx\`** with **\`I18nextProvider\`**, and preloads **\`import \"./i18n\"\`** from **\`router.tsx\`** so **\`react-i18next\`** receives a real **\`i18next\`** instance (replacing **\`next-i18next\`** / \`serverSideTranslations\`).
- Wire **\`react-i18next\`** / **Paraglide** to the active locale (often \`Route.useParams().locale\` or router \`rewrite\` for URL localization — see the same doc and the [Paraglide + TanStack](https://github.com/TanStack/router/tree/main/examples/react/i18n-paraglide) example).
- Internal **\`Link to="…"\`** paths may need \`params\` updates so the optional \`locale\` is preserved when switching languages.
- **Strict TypeScript** — \`Link to={...}\` literals often break after routes move under \`/{-$locale}/…\`: internal paths must match the generated route union (\`params\`, \`from\`/validated \`to\`), or temporarily wrap/replace \`Link\` until every href matches the router tree (\`vite dev\`/build regenerates types).

## 1. In-repo TODO markers (start here)

The workflow inserts single-line source comments you can search for:

\`\`\`bash
rg '// TODO:'
\`\`\`

- **R10** — \`// TODO: … Route.loader …\` before \`createFileRoute\` components that still use **top-level \`await\`** (move data into \`Route.loader\` or server functions).
- **R10b** — the same \`// TODO:\` prefix **immediately before each surviving \`from "next/…"\` import**, plus one file-level note for **\`middleware.ts\` / \`middleware.tsx\`** when it still imports from Next.
- **R4e** (\`next/cache\`) — a banner \`// TODO:\` (search \`(R4e)\`) marks files where the codemod replaced \`next/cache\`; finalize TanStack Query: \`queryClient\` + \`QueryClientProvider\` (or app root wiring), consistent \`invalidateQueries\` / \`useQuery\` keys, and \`unstable_cache\` / \`unstable_noStore\` semantics via \`staleTime\`, \`gcTime\`, refetch — [invalidation guide](https://tanstack.com/query/latest/docs/framework/react/guides/query-invalidation), [overview](https://tanstack.com/query/latest/docs/framework/react/overview).

- **R4f** (\`next/headers\`) — a banner \`// TODO:\` (search \`(R4f)\`) when \`cookies().get\` / \`headers().get\` were rewritten via \`next-headers-bridge.ts\`; still pass a real \`Request\` instead of \`undefined\`, and handle any survivors (\`draftMode\`, cookie writes, bare \`headers()\`) manually — [router context](https://tanstack.com/router/latest/docs/framework/react/guide/router-context).

- **R4g** (\`next/navigation\`) — a banner \`// TODO:\` (search \`(R4g)\`) when \`redirect\` / \`useRouter\` patterns were rewritten; must \`throw redirect()\` in loaders/beforeLoad, use \`useNavigate()\` on the client — [navigation guide](https://tanstack.com/router/latest/docs/framework/react/guide/navigation).

- **R4h** (\`next/server\`) — a banner \`// TODO:\` (search \`(R4h)\`) when \`NextRequest\`/\`NextResponse\` were mapped to Fetch \`Request\`/\`Response\`; port any remaining helpers (\`after\`, \`connection\`, \`NextResponse.next\`, etc.) to TanStack server routes — [server routes](https://tanstack.com/start/latest/docs/framework/react/guide/server-routes).

- **R4i** (\`next/og\`) — imports are pointed at \`@vercel/og\` (dependency added in R11); verify runtime and any experimental OG APIs.

Resolve or delete each marker as you port the code. Safe \`next/dynamic\` / external \`next/script\` patterns are already rewritten earlier in the workflow; anything left usually needs a manual decision.

## 2. Install and run

- Install dependencies (\`pnpm install\`, \`yarn\`, or \`npm install\`).
- **Lockfiles** — R11 edits \`package.json\` only; it does **not** rewrite \`package-lock.json\`, \`pnpm-lock.yaml\`, or \`yarn.lock\`. Run a **normal** install once after the codemod so your lockfile matches the manifest; **\`npm ci\` / frozen-lockfile installs will fail** until you do.
- If **\`next-auth\`**, **\`next-i18next\`**, or **\`@sentry/nextjs\`** (etc.) remain, replace or reconfigure them — **\`next\`** is removed from \`package.json\` and those packages often expect it as a peer.
- Run **\`pnpm dev\` / \`npm run dev\` / \`vite dev\`** and fix compile errors.

## 3. Review (not fully automatable)

- **Metadata / SEO** — compare \`head()\` with what you had under \`export const metadata\`.
- **Monorepos** — other packages may still target Next; use **\`-t\`** on one app when you want a narrow run. Shared code that imports **\`next/navigation\`** still needs **\`@tanstack/react-router\`** at call sites.
- **Tooling** — when there are no Next-adjacent peers, the codemod adjusts **\`tsconfig\`**, **\`.eslintrc.json\`**, **\`README.md\`**, and **\`.github/workflows/\`**. Double-check **flat ESLint** (\`eslint.config.*\`), root CI, and **JSONC** by hand.
- **Pages Router leftovers** — if the project used \`pages/\`, any files that were not merged into routes (e.g. \`_document.tsx\`) were moved to **\`migrated-from-pages/\`** at the package root. Port or delete them, then remove that folder.
`;

const REFERENCE_LINKS = `## Reference links

- [TanStack Query — overview](https://tanstack.com/query/latest/docs/framework/react/overview)
- [TanStack Query — invalidation](https://tanstack.com/query/latest/docs/framework/react/guides/query-invalidation)
- [TanStack Router — routing](https://tanstack.com/router/latest/docs/framework/react/routing/routing-concepts)
- [Server routes](https://tanstack.com/start/latest/docs/framework/react/guide/server-routes)
- [Server functions](https://tanstack.com/start/latest/docs/framework/react/guide/server-functions)
`;

const codemod: Codemod<JSON_TYPES> = async (root, options) => {
  const file = getFilename(root);
  if (!file.endsWith("/package.json") && !file.endsWith("package.json")) {
    return null;
  }

  const rootNode = root.root();
  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(rootNode.text()) as Record<string, unknown>;
  } catch {
    return null;
  }

  const deps = mergedDeps(pkg);
  if (!deps["@tanstack/react-start"]) {
    return null;
  }

  const dir = inferPackageRoot(file);
  const pkgRoot = normalizePath(dir);
  const r10 = getState<R10Accum>(`mtg:r10:${pkgRoot}`);
  const r10b = getState<R10bAccum>(`mtg:r10b:${pkgRoot}`);
  const summary = buildMigrationRunSummarySection({
    packageRoot: relativeToTargetDir(dir, options.targetDir ?? dir),
    stateKeyRoot: pkgRoot,
    r10,
    r10b,
    r10Metric,
    r10bMetric,
  });
  const body = `${GUIDE.trimEnd()}\n\n${summary.trimEnd()}\n\n${REFERENCE_LINKS.trimEnd()}\n`;
  writeFileSync(join(dir, OUTFILE), body);
  mergeMigrationGitignore(dir);
  return null;
};

export default codemod;
