import { Outlet, createRootRoute, HeadContent, Scripts } from "@tanstack/react-router";
import appCss from "./globals.css?url";

export const Route = createRootRoute({
    head: () => ({
      meta: [{ title: "Create Next App" }, { name: "description", content: "Generated by create next app" }, { property: "og:title", content: "Next App" }, { property: "og:description", content: "og description" }, { property: "og:image", content: "https://example.com/og.png" }, { name: "twitter:card", content: "summary" }, { name: "twitter:title", content: "Twitter title" }],
    }),
  component: RootLayout,
});

function RootLayout() {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        <Outlet />
        <Scripts />
      </body>
    </html>
  );
}
